# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: clang-format lint
        # You may pin to the exact commit or the version.
        # uses: DoozyX/clang-format-lint-action@2ec1a72dfb593e52255693c9039e6d94984187dc
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          # Source folder to check formatting
          source: . # optional, default is .
          # Folder to exclude from formatting check
          exclude: none # optional, default is none
          # List of extensions to check
          extensions: cpp,h # optional, default is c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx
          # Version of clang-format
          clangFormatVersion: 9 # optional, default is 9
          # Formatting style to use
          style: file # optional, default is file
          # Just fix files (`clang-format -i`) instead of returning a diff
          inplace: false # optional
